- name: Deploy MariaDB Docker container
  hosts: testHost
  become: yes
  vars_files:
    - secrets.yaml
  tasks:
    - name: Pull MariaDB Docker image
      command: docker pull mariadb

    - name: Run MariaDB Docker container
      command: >
        docker run --name mariadb -p 3306:3306 -e MYSQL_ROOT_PASSWORD="{{ mysql_root_password }}" -v /home/david/sqlbase:/var/lib/mysql -d mariadb
